-- Phase 3: versioned claim/evidence and pre-publication safety records.
CREATE TABLE IF NOT EXISTS article_versions (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,article_id TEXT NOT NULL,version_no INTEGER NOT NULL,draft_json TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'GENERATING',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_article_version_unique ON article_versions(client_id,article_id,version_no);
CREATE TABLE IF NOT EXISTS content_claims (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,article_version_id TEXT NOT NULL,article_id TEXT NOT NULL,paragraph_index INTEGER NOT NULL,sentence TEXT NOT NULL,claim_text TEXT NOT NULL,claim_type TEXT NOT NULL,risk_level TEXT NOT NULL,requires_verification INTEGER NOT NULL,verification_status TEXT NOT NULL,verification_reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_claim_version_paragraph_text ON content_claims(article_version_id,paragraph_index,claim_text);
CREATE INDEX IF NOT EXISTS idx_claim_client_article ON content_claims(client_id,article_id);
CREATE TABLE IF NOT EXISTS claim_sources (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,claim_id TEXT NOT NULL,source_type TEXT NOT NULL,source_url TEXT NOT NULL DEFAULT '',source_title TEXT NOT NULL DEFAULT '',publisher TEXT NOT NULL DEFAULT '',published_at TEXT,accessed_at TEXT NOT NULL,evidence_excerpt TEXT NOT NULL DEFAULT '',evidence_strength TEXT NOT NULL,supports_claim INTEGER NOT NULL DEFAULT 0,contradiction_detected INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_claim_source_unique ON claim_sources(claim_id,source_type,source_url,evidence_excerpt);
CREATE TABLE IF NOT EXISTS article_eeat_assessments (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,article_version_id TEXT NOT NULL,experience_score REAL NOT NULL,expertise_score REAL NOT NULL,authoritativeness_score REAL NOT NULL,trust_score REAL NOT NULL,missing_evidence_json TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_eeat_version ON article_eeat_assessments(article_version_id);
CREATE TABLE IF NOT EXISTS article_ymyl_assessments (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,article_version_id TEXT NOT NULL,risk TEXT NOT NULL,reason TEXT NOT NULL,required_reviews_json TEXT NOT NULL DEFAULT '[]',created_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_ymyl_version ON article_ymyl_assessments(article_version_id);
CREATE TABLE IF NOT EXISTS human_review_queue (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,article_version_id TEXT NOT NULL,status TEXT NOT NULL,reason_codes_json TEXT NOT NULL DEFAULT '[]',notes TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_human_review_version ON human_review_queue(article_version_id);
CREATE TABLE IF NOT EXISTS internal_link_candidates (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,article_version_id TEXT NOT NULL,source_article_id TEXT NOT NULL,target_article_id TEXT NOT NULL,source_url TEXT NOT NULL DEFAULT '',target_url TEXT NOT NULL,anchor_text TEXT NOT NULL,anchor_type TEXT NOT NULL,relation_type TEXT NOT NULL,relevance_score REAL NOT NULL,intent_match INTEGER NOT NULL DEFAULT 0,status TEXT NOT NULL,validation_reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL,updated_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_link_candidate_unique ON internal_link_candidates(article_version_id,target_article_id,anchor_text);
CREATE TABLE IF NOT EXISTS article_quality_reviews (id TEXT PRIMARY KEY,client_id TEXT NOT NULL,article_version_id TEXT NOT NULL,total_score REAL NOT NULL,breakdown_json TEXT NOT NULL,auto_publish_status TEXT NOT NULL,reasons_json TEXT NOT NULL DEFAULT '[]',manual_publish_allowed INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL);
CREATE UNIQUE INDEX IF NOT EXISTS idx_quality_version ON article_quality_reviews(article_version_id);
