import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("..",import.meta.url);const source=(path)=>readFile(new URL(path,root),"utf8");

test("Final remediation: Claude uses first-class role system prompts and prompt versions",async()=>{const worker=await source("cloud-runner/src/index.ts");for(const value of ["WRITER","FACT_CHECKER","QUALITY_AUDITOR","SERP_ANALYST","AUTOPILOT_STRATEGIST","prompt_version","system:"])assert.match(worker,new RegExp(value));assert.match(worker,/"WRITER"[,)\s]/);assert.match(worker,/"FACT_CHECKER"[,)\s]/);});
test("Final remediation: incomplete Content Brief blocks a Writer job without an empty-object fallback",async()=>{const api=await source("app/api/[[...path]]/route.ts"),worker=await source("cloud-runner/src/index.ts");for(const value of ["completeContentBrief","CONTENT_BRIEF_INCOMPLETE","persistedBrief"])assert.match(api,new RegExp(value));assert.doesNotMatch(worker,/c\.contentBrief \|\| p\.brief \|\| \{\}/);});
test("Final remediation: audit NG creates a finite, immutable revision instruction and a next-version job",async()=>{const [api,sql]=await Promise.all([source("app/api/[[...path]]/route.ts"),source("drizzle/0013_final_audit_remediation.sql")]);for(const value of ["article_revision_instructions","idx_revision_instruction_once","max_auto_revisions","revisionOfVersionId","revisionInstructionId","revision_requested","revisionCount<maxAutoRevisions","ON CONFLICT(client_id,from_article_version_id) DO NOTHING"])assert.match(`${api}\n${sql}`,new RegExp(value.replace(/[()]/g,"\\$&")));});
test("Final remediation: revisions receive their prior version and structured instruction while preserving version records",async()=>{const [api,worker]=await Promise.all([source("app/api/[[...path]]/route.ts"),source("cloud-runner/src/index.ts")]);for(const value of ["revisionSource","revisionInstruction","元Article Version","構造化Revision Instruction","INSERT INTO article_versions"])assert.match(`${api}\n${worker}`,new RegExp(value));});
