import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const root=new URL("..",import.meta.url);const source=(path)=>readFile(new URL(path,root),"utf8");

test("Final audit: Writer receives the persisted Content Brief and only approved confirmed sources",async()=>{const [api,worker]=await Promise.all([source("app/api/[[...path]]/route.ts"),source("cloud-runner/src/index.ts")]);assert.match(api,/\["article_generate", "content_intelligence_review"\]/);assert.match(api,/item\.approved && item\.is_canonical && !item\.archived/);assert.match(api,/SELECT b\.\* FROM content_briefs/);assert.match(worker,/Content Brief:\$\{compact\(c\.contentBrief/);assert.match(worker,/Confirmed Primary Sources:\$\{compact\(c\.sources/);});
test("Final audit: Writer, fact checker, and final quality gate are separate calls and version records",async()=>{const [api,worker]=await Promise.all([source("app/api/[[...path]]/route.ts"),source("cloud-runner/src/index.ts")]);assert.match(worker,/async function article\(/);assert.match(worker,/async function contentIntelligence\(/);assert.match(worker,/AIの記憶でVERIFIEDにしない/);assert.match(worker,/searchIntent.*informationQuality.*originalValue.*eeat.*structureUx.*seo.*conversion.*safetyFactCheck/s);for(const item of ["content_claims","claim_sources","article_quality_reviews","article_ymyl_assessments","human_review_queue"])assert.match(api,new RegExp(item));});
test("Final audit: REWRITE and EXPAND keep the mapped article id and never create a second WordPress post automatically",async()=>{const api=await source("app/api/[[...path]]/route.ts");assert.match(api,/generatedForArticleId/);assert.match(api,/articleId \|\| job\.id/);assert.match(api,/autopilotExistingArticleUpdate/);assert.match(api,/autopilotActionType:articlePayload\.autopilotActionType/);assert.match(api,/\["REWRITE","EXPAND"\]/);assert.match(api,/wp\?\.secret_cipher && !autopilotExistingArticleUpdate/);assert.match(api,/autoEligibility\.eligible&&!autopilotExistingArticleUpdate/);});
test("Final audit: queued Autopilot work rechecks client pause and the global kill switch immediately before execution",async()=>{const api=await source("app/api/[[...path]]/route.ts");for(const item of ["worker/autopilot-execute","kill_switch_enabled","clientAutopilot","EXECUTION_STOPPED_BY_KILL_SWITCH","status='SKIPPED'"])assert.match(api,new RegExp(item));});
test("Final audit: unsafe actions never bypass review; status history and WordPress gates remain versioned",async()=>{const api=await source("app/api/[[...path]]/route.ts");for(const item of ["MERGE","REDIRECT","TITLE_OPTIMIZATION","INTERNAL_LINK","HUMAN_REVIEW_REQUIRED","transitionArticleStatus","wordpress_article_versions","wordpress_publish_history","article_seo_data","AUTO_PUBLISH_OFF"])assert.match(api,new RegExp(item));});
