import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { createMockWordPressAdapter } from "../lib/wordpress-adapter.mjs";
import { insertMinimalInternalLink, targetAlreadyLinked } from "../lib/internal-link-execution.mjs";
const source=(file)=>readFile(new URL(`../${file}`,import.meta.url),"utf8");

test("INTERNAL_LINK UI is connected to owner-scoped history, controls, safety states, snapshot, and measurement",async()=>{const [ui,api]=await Promise.all([source("app/seo-loop-app.tsx"),source("app/api/[[...path]]/route.ts")]);for(const token of ["Internal Link Proposal","internalLinkHistory","internalLinkMeasurements","internalLinkCommand","Approve","Reject","Execute","Rollback","ALREADY_LINKED","Snapshot","DATA_NOT_AVAILABLE","既存WordPress記事へ承認済みURLの内部リンクを追加します。新規記事は作成しません。"]){assert.ok(ui.includes(token));}for(const token of ["internal_link_execution_history WHERE client_id=?","internalLinkMeasurements","ownedClient(clientId,owner)"]){assert.ok(api.includes(token));}});

test("dedicated safe-manual E2E contract: mapping URL → placement → snapshot → UPDATE_EXISTING → immutable version/history → measurements",async()=>{const wp=createMockWordPressAdapter({posts:[{id:"1",title:"Source",slug:"source",content:"<h1>Same</h1><p>Read target guide.</p>",categories:[1],tags:[2],featured_media:3,meta:{seo:"same"}}]}),target="https://example.test/target",before=await wp.fetchPost("1"),change=insertMinimalInternalLink(before.content,target,{anchor_text:"target guide",placement_reference:"target guide",confidence:"HIGH"});const snapshot=structuredClone(before);const after=await wp.update("1",{content:change.html});assert.equal(after.id,"1");assert.equal(after.slug,snapshot.slug);assert.deepEqual(after.categories,snapshot.categories);assert.deepEqual(after.tags,snapshot.tags);assert.equal(after.featured_media,snapshot.featured_media);assert.deepEqual(after.meta,snapshot.meta);assert.equal(after.content.replace(change.link,"target guide"),snapshot.content);});

test("dedicated AUTO safe contract is queued only after placement safety, while recommend-only has no WordPress write",async()=>{const api=await source("app/api/[[...path]]/route.ts");for(const token of ["AUTO_EXECUTE_SAFE_ACTIONS","internal_link_update","execution_status='QUEUED'","RECOMMEND_ONLY","HUMAN_REVIEW_REQUIRED"]){assert.ok(api.includes(token));}});

test("duplicate, snapshot failure, safety, client boundary, and retry contracts prevent writes",async()=>{const [worker,api,migration]=await Promise.all([source("cloud-runner/src/index.ts"),source("app/api/[[...path]]/route.ts"),source("drizzle/0016_internal_link_execution.sql")]);assert.equal(targetAlreadyLinked('<a href="https://example.test/t">x</a>','https://example.test/t'),true);for(const token of ["ALREADY_LINKED","worker/internal-link-snapshot","INTERNAL_LINK_EXECUTION_BLOCKED","kill_switch_enabled","paused","client_id=? AND action_id=?"]){assert.ok((worker+api).includes(token));}assert.ok(migration.includes("idx_internal_link_execution_idempotency"));});

test("before, 7d, and 28d source/target observations reuse autopilot_measurements without inventing missing data",async()=>{const api=await source("app/api/[[...path]]/route.ts");for(const token of ["internalLinkMetricSummary","window_days,metrics_json,result_status","before,dataStatus","source,target","DATA_NOT_AVAILABLE","[7,28]"]){assert.ok(api.includes(token));}});
