import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
import { ACTION_TYPES, evaluateWeeklyAutopilot, freshnessStatus, measureAutopilot } from "../lib/seo-autopilot.mjs";

const root=new URL("..",import.meta.url); const source=(path)=>readFile(new URL(path,root),"utf8");
const fresh={gsc:"FRESH",ga4:"FRESH",serp:"FRESH",ubersuggest:"FRESH"};
const base={freshness:fresh,gsc:{impressions:1000,position:6,ctr:.03},ga4:{sessions:100,conversions:2},serp:{searchIntent:"informational"},keyword:{priorityScore:70},article:{qualityScore:97,ymylRisk:"LOW"},primarySourceReady:true};

test("Phase 5はAutopilot設定・週次Run・Action・Measurement・AuditをD1へ保存する",async()=>{const [sql,server]=await Promise.all([source("drizzle/0012_phase5_seo_autopilot.sql"),source("lib/server.ts")]);for(const item of ["client_autopilot_settings","global_autopilot_settings","autopilot_runs","autopilot_actions","autopilot_measurements","autopilot_audit_log","idx_autopilot_primary_action"]) {assert.match(sql,new RegExp(item));assert.match(server,new RegExp(item));}});
test("8つのAction TypeとNO_ACTIONを実データルールとして扱う",()=>{assert.deepEqual(ACTION_TYPES,["NEW_ARTICLE","REWRITE","EXPAND","TITLE_OPTIMIZATION","INTERNAL_LINK","MERGE","REDIRECT","NO_ACTION"]);const title=evaluateWeeklyAutopilot({...base,article:{id:"a",qualityScore:97},gsc:{impressions:3000,position:5,ctr:.01}});assert.equal(title.recommended.actionType,"TITLE_OPTIMIZATION");const expand=evaluateWeeklyAutopilot({...base,article:{id:"a",qualityScore:97},gsc:{impressions:300,position:9,ctr:.04},serp:{searchIntent:"informational",contentGap:true}});assert.equal(expand.recommended.actionType,"EXPAND");const rewrite=evaluateWeeklyAutopilot({...base,article:{id:"a",qualityScore:90},gsc:{impressions:300,position:18,ctr:.04,positionDelta:4}});assert.equal(rewrite.recommended.actionType,"REWRITE");const link=evaluateWeeklyAutopilot({...base,article:{id:"a",qualityScore:97,orphan:true,relatedArticleCount:2},gsc:{impressions:300,position:8,ctr:.04}});assert.equal(link.recommended.actionType,"INTERNAL_LINK");const created=evaluateWeeklyAutopilot({...base,article:{qualityScore:0},keyword:{priorityScore:90},serp:{searchIntent:"commercial",requiredTopics:["比較"]}});assert.equal(created.recommended.actionType,"NEW_ARTICLE");const merge=evaluateWeeklyAutopilot({...base,cannibalization:{risk:"HIGH"},article:{id:"a",sourceUrl:"https://a.test/a",targetUrl:"https://a.test/b"}});assert.equal(merge.recommended.actionType,"MERGE");assert.ok(merge.candidates.some((item)=>item.actionType==="REDIRECT"&&item.humanReview));const none=evaluateWeeklyAutopilot({...base,freshness:{gsc:"NOT_AVAILABLE",ga4:"NOT_AVAILABLE",serp:"STALE",ubersuggest:"NOT_AVAILABLE"}});assert.equal(none.recommended.actionType,"NO_ACTION");});
test("Data Freshnessと欠損データは推測せずDATA_NOT_AVAILABLE相当のNO_ACTIONへ落とす",()=>{assert.equal(freshnessStatus(null),"NOT_AVAILABLE");assert.equal(freshnessStatus(new Date(Date.now()-72*3600_000).toISOString(),24),"STALE");const result=evaluateWeeklyAutopilot({...base,freshness:{gsc:"NOT_AVAILABLE",ga4:"NOT_AVAILABLE",serp:"NOT_AVAILABLE",ubersuggest:"NOT_AVAILABLE"}});assert.equal(result.recommended.actionType,"NO_ACTION");assert.equal(result.confidence,"LOW");});
test("Autopilot Mode・Safety・YMYL・Cannibal HIGHは自動公開を許可しない",()=>{const ymyl=evaluateWeeklyAutopilot({...base,article:{id:"a",qualityScore:97,ymylRisk:"HIGH"},gsc:{impressions:1000,position:8,ctr:.01}});assert.equal(ymyl.safety.autoPublishAllowed,false);assert.equal(ymyl.safety.ymylHigh,true);const cannibal=evaluateWeeklyAutopilot({...base,cannibalization:{risk:"HIGH"},article:{id:"a"}});assert.notEqual(cannibal.recommended.actionType,"NEW_ARTICLE");assert.equal(cannibal.safety.humanReviewRequired,true);});
test("Before Snapshotと7d/28d MeasurementはImproved・Neutral・Declined・Insufficient Dataを返す",()=>{assert.equal(measureAutopilot({},{}).status,"INSUFFICIENT_DATA");assert.equal(measureAutopilot({clicks:10,sessions:4},{clicks:12,sessions:6}).status,"IMPROVED");assert.equal(measureAutopilot({clicks:10,sessions:4},{clicks:10,sessions:4}).status,"NEUTRAL");assert.equal(measureAutopilot({clicks:10,sessions:4},{clicks:8,sessions:2}).status,"DECLINED");});
test("7日・28日の測定結果は同じAction Typeの次回優先順位へ有限に反映する",()=>{const input={...base,article:{id:"a",qualityScore:97},gsc:{impressions:3000,position:5,ctr:.01},learning:{byAction:{TITLE_OPTIMIZATION:{samples:6,successRate:.2}}}};const result=evaluateWeeklyAutopilot(input);assert.equal(result.recommended.actionType,"TITLE_OPTIMIZATION");assert.equal(result.learning.status,"APPLIED");assert.equal(result.learning.adjustment,-8);assert.equal(result.recommended.score,result.candidates.find((item)=>item.actionType==="TITLE_OPTIMIZATION").score);});
test("Weekly Cron・Queue・既存Pipeline再利用・有限Retry・Idempotencyを接続する",async()=>{const [api,sql,worker]=await Promise.all([source("app/api/[[...path]]/route.ts"),source("drizzle/0012_phase5_seo_autopilot.sql"),source("cloud-runner/src/index.ts")]);for(const item of ["worker/autopilot-weekly","autopilot_execute","MANUAL","article_generate","HUMAN_REVIEW_REQUIRED","GLOBAL_KILL_SWITCH","AUTOPILOT_PAUSED"])assert.match(api,new RegExp(item));assert.match(sql,/idx_autopilot_primary_action/);for(const item of ["worker/autopilot-weekly","autopilot_execute","message.retry({ delaySeconds: 60 })","autopilot_audit_log"])assert.match(worker,new RegExp(item.replace(/[{}()]/g,"\\$&")));});
test("Autopilot API・Manual Override・History・Client Isolation・UIを提供する",async()=>{const [api,ui]=await Promise.all([source("app/api/[[...path]]/route.ts"),source("app/seo-loop-app.tsx")]);for(const item of ["autopilotRoute","ownedClient(clientId, owner)","APPROVE","REJECT","CHANGE_ACTION","EXECUTE_NOW","PAUSE","autopilot_actions","autopilot_measurements"])assert.match(api,new RegExp(item.replace(/[()]/g,"\\$&")));for(const item of ["SEO Autopilot","Data Freshness","Recommended Action","Weekly History","Measurement","PAUSE AUTOPILOT","Global Kill Switch"])assert.match(ui,new RegExp(item));});
