CREATE TABLE IF NOT EXISTS production_projects (
  id TEXT PRIMARY KEY, youtube_url TEXT NOT NULL DEFAULT '', youtube_title TEXT NOT NULL DEFAULT '', transcript TEXT NOT NULL DEFAULT '', transcript_chars INTEGER NOT NULL DEFAULT 0,
  direction TEXT NOT NULL DEFAULT '', challenger_name TEXT NOT NULL DEFAULT '', challenger_company TEXT NOT NULL DEFAULT '', special_guest TEXT NOT NULL DEFAULT '', mc_name TEXT NOT NULL DEFAULT '',
  strict_evidence INTEGER NOT NULL DEFAULT 1, image_suggestions INTEGER NOT NULL DEFAULT 1, article_limit INTEGER NOT NULL DEFAULT 1, status TEXT NOT NULL DEFAULT 'INPUT', created_at TEXT NOT NULL, updated_at TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS uploaded_files (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, object_key TEXT NOT NULL UNIQUE, name TEXT NOT NULL, content_type TEXT NOT NULL, size INTEGER NOT NULL, extraction_status TEXT NOT NULL DEFAULT 'PENDING', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS keyword_candidates (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, keyword TEXT NOT NULL, related_keywords TEXT NOT NULL DEFAULT '[]', search_intent TEXT NOT NULL, reader TEXT NOT NULL, angle TEXT NOT NULL, relevance TEXT NOT NULL, duplication_risk TEXT NOT NULL DEFAULT 'low', status TEXT NOT NULL DEFAULT 'PROPOSED', created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_keyword_candidates_project ON keyword_candidates(project_id, created_at DESC);
CREATE TABLE IF NOT EXISTS articles (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, candidate_id TEXT, title TEXT NOT NULL, title_tag TEXT NOT NULL DEFAULT '', meta_description TEXT NOT NULL DEFAULT '', slug TEXT NOT NULL DEFAULT '', catch_copy TEXT NOT NULL DEFAULT '', main_keyword TEXT NOT NULL, related_keywords TEXT NOT NULL DEFAULT '[]', search_intent TEXT NOT NULL DEFAULT '', reader TEXT NOT NULL DEFAULT '', angle TEXT NOT NULL DEFAULT '', category_id TEXT NOT NULL DEFAULT '', category_name TEXT NOT NULL DEFAULT '', body_html TEXT NOT NULL DEFAULT '', evidence_json TEXT NOT NULL DEFAULT '[]', image_suggestions_json TEXT NOT NULL DEFAULT '[]', quality_json TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'DRAFT', wordpress_post_id TEXT, wordpress_edit_url TEXT, wordpress_status TEXT NOT NULL DEFAULT 'NOT_SENT', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_articles_project ON articles(project_id, updated_at DESC);
CREATE TABLE IF NOT EXISTS site_settings (id TEXT PRIMARY KEY, site_name TEXT NOT NULL DEFAULT '', site_url TEXT NOT NULL DEFAULT '', category_cache TEXT NOT NULL DEFAULT '[]', updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS encrypted_connections (id TEXT PRIMARY KEY, provider TEXT NOT NULL UNIQUE, public_config TEXT NOT NULL DEFAULT '{}', secret_cipher TEXT NOT NULL DEFAULT '', status TEXT NOT NULL DEFAULT 'NOT_CONFIGURED', updated_at TEXT NOT NULL);
