type VerifyResult = { publicConfig: Record<string, unknown>; secret: Record<string, unknown> };
async function request(url: string, options: RequestInit = {}) { const response = await fetch(url, options); const raw = await response.text(); const contentType = response.headers.get("content-type") || ""; let payload: Record<string, any> = {}; try { payload = raw ? JSON.parse(raw) : {}; } catch { if (contentType.includes("text/html") || raw.trimStart().startsWith("<")) throw new Error("WordPress REST APIがHTMLを返しました。WordPress URLには「/wp-admin」や「/wp-login.php」を含めず、サイトのトップURLを入力してください。"); throw new Error("接続先APIがJSONを返しませんでした。"); } if (!response.ok) throw new Error(payload.message || payload.error?.message || `API error (${response.status})`); return payload; }
function url(value: unknown) { const parsed = new URL(String(value || "")); if (!['https:','http:'].includes(parsed.protocol)) throw new Error("URLが正しくありません。"); return parsed.toString().replace(/\/$/, ""); }
export function wordpressBase(value: unknown) { const parsed = new URL(url(value)); parsed.search = ""; parsed.hash = ""; parsed.pathname = parsed.pathname.replace(/\/(?:wp-admin(?:\/.*)?|wp-json(?:\/.*)?|wp-login\.php)$/i, "").replace(/\/$/, ""); return parsed.toString().replace(/\/$/, ""); }
function basic(user: unknown, password: unknown) { return `Basic ${btoa(`${user}:${password}`)}`; }
function xml(value: unknown) { return String(value ?? "").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&apos;"); }
function xmlString(value: unknown) { return `<param><value><string>${xml(value)}</string></value></param>`; }
function xmlText(body: string, name: string) { const match = body.match(new RegExp(`<name>${name}<\\/name>\\s*<value>\\s*<string>([\\s\\S]*?)<\\/string>`, "i")); return match?.[1]?.replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&apos;/g,"'") || ""; }
export async function wordpressXmlRpcLogin(siteUrl: unknown, username: unknown, applicationPassword: unknown) { const base = wordpressBase(siteUrl); const body = `<?xml version="1.0"?><methodCall><methodName>wp.getUsersBlogs</methodName><params>${xmlString(username)}${xmlString(applicationPassword)}</params></methodCall>`; const response = await fetch(`${base}/xmlrpc.php`, { method:"POST", headers:{"Content-Type":"text/xml"}, body, signal:AbortSignal.timeout(15000) }); const raw = await response.text(); if (!response.ok || /<fault>/i.test(raw)) throw new Error(xmlText(raw,"faultString") || "XML-RPC認証に失敗しました。"); const name = xmlText(raw,"blogName") || xmlText(raw,"url") || base; const blogId = xmlText(raw,"blogid") || "1"; return { base, name, blogId }; }
export async function wordpressXmlRpcDraft(siteUrl: unknown, username: unknown, applicationPassword: unknown, title: string, content: string) { const login = await wordpressXmlRpcLogin(siteUrl, username, applicationPassword); const struct = `<struct><member><name>post_type</name><value><string>post</string></value></member><member><name>post_status</name><value><string>draft</string></value></member><member><name>post_title</name><value><string>${xml(title)}</string></value></member><member><name>post_content</name><value><string>${xml(content)}</string></value></member></struct>`; const body = `<?xml version="1.0"?><methodCall><methodName>wp.newPost</methodName><params>${xmlString(login.blogId)}${xmlString(username)}${xmlString(applicationPassword)}<param><value>${struct}</value></param></params></methodCall>`; const response = await fetch(`${login.base}/xmlrpc.php`, { method:"POST", headers:{"Content-Type":"text/xml"}, body, signal:AbortSignal.timeout(20000) }); const raw = await response.text(); if (!response.ok || /<fault>/i.test(raw)) throw new Error(xmlText(raw,"faultString") || "XML-RPC下書き入稿に失敗しました。"); const postId = raw.match(/<string>(\d+)<\/string>/)?.[1]; if (!postId) throw new Error("XML-RPCの投稿IDを取得できませんでした。"); return { id: Number(postId), editUrl: `${login.base}/wp-admin/post.php?post=${postId}&action=edit` }; }

export const connectorFields: Record<string, Array<{name:string;label:string;type?:string;required?:boolean}>> = {
  anthropic:[{name:"apiKey",label:"Anthropic APIキー",type:"password"}],
  wordpress:[{name:"siteUrl",label:"WordPress URL",type:"url"},{name:"username",label:"ユーザー名"},{name:"applicationPassword",label:"Application Password",type:"password"}],
  image:[{name:"apiKey",label:"OpenAI APIキー",type:"password"}],
  instagram:[{name:"accessToken",label:"Metaアクセストークン",type:"password"}],
  x:[{name:"bearerToken",label:"X Bearer Token",type:"password"},{name:"username",label:"対象ユーザー名（@なし）"}],
  notion:[{name:"token",label:"Notion Integration Token",type:"password"}],
  pagespeed:[{name:"siteUrl",label:"計測URL",type:"url"},{name:"apiKey",label:"APIキー（任意）",type:"password",required:false}]
};

export async function verify(connector: string, input: Record<string, string>, metaVersion = "v23.0"): Promise<VerifyResult> {
  if (connector === "anthropic") { const models=await request("https://api.anthropic.com/v1/models?limit=1",{headers:{"x-api-key":input.apiKey,"anthropic-version":"2023-06-01"}}); return { publicConfig:{resourceName:"Claude API",model:models.data?.[0]?.id||"Claude"},secret:{apiKey:input.apiKey} }; }
  if (connector === "wordpress") { const siteUrl=wordpressBase(input.siteUrl); try { const me=await request(`${siteUrl}/wp-json/wp/v2/users/me?context=edit`,{headers:{Authorization:basic(input.username,input.applicationPassword)}}); return { publicConfig:{siteUrl,username:input.username,resourceName:me.name||me.slug,authMode:"rest"},secret:{applicationPassword:input.applicationPassword} }; } catch (restError) { const xmlrpc=await wordpressXmlRpcLogin(siteUrl,input.username,input.applicationPassword); return { publicConfig:{siteUrl,username:input.username,resourceName:xmlrpc.name,authMode:"xmlrpc"},secret:{applicationPassword:input.applicationPassword} }; } }
  if (connector === "image") { const model=await request("https://api.openai.com/v1/models/gpt-image-2",{headers:{Authorization:`Bearer ${input.apiKey}`}}); return { publicConfig:{resourceName:model.id||"gpt-image-2"},secret:{apiKey:input.apiKey} }; }
  if (connector === "notion") { const me=await request("https://api.notion.com/v1/users/me",{headers:{Authorization:`Bearer ${input.token}`,"Notion-Version":"2022-06-28"}}); return { publicConfig:{resourceName:me.name||"Notion integration",accountId:me.id},secret:{token:input.token} }; }
  if (connector === "x") { const username=input.username.replace(/^@/,""); const user=await request(`https://api.x.com/2/users/by/username/${encodeURIComponent(username)}?user.fields=name,username`,{headers:{Authorization:`Bearer ${input.bearerToken}`}}); return { publicConfig:{resourceName:`@${user.data?.username||username}`,accountId:user.data?.id,username},secret:{bearerToken:input.bearerToken} }; }
  if (connector === "instagram") { const fields=encodeURIComponent("id,name,accounts.limit(100){id,name,instagram_business_account{id,username,name}}"); const me=await request(`https://graph.facebook.com/${metaVersion}/me?fields=${fields}&access_token=${encodeURIComponent(input.accessToken)}`); const accounts=(me.accounts?.data||[]).filter((item:any)=>item.instagram_business_account).map((item:any)=>({pageId:item.id,pageName:item.name,id:item.instagram_business_account.id,username:item.instagram_business_account.username||""})); return { publicConfig:{resourceName:`${accounts.length}件のInstagram`,accounts,selectedAccountId:accounts[0]?.id||""},secret:{accessToken:input.accessToken} }; }
  if (connector === "pagespeed") { const siteUrl=url(input.siteUrl); const params=new URLSearchParams({url:siteUrl,strategy:"mobile",category:"performance"}); if(input.apiKey)params.set("key",input.apiKey); const data=await request(`https://www.googleapis.com/pagespeedonline/v5/runPagespeed?${params}`); return { publicConfig:{resourceName:data.id||siteUrl,siteUrl,score:data.lighthouseResult?.categories?.performance?.score??null},secret:{apiKey:input.apiKey||""} }; }
  throw new Error("この連携はローカルワーカーまたはGoogle OAuthから接続します。");
}
