import { env } from "cloudflare:workers";

export type Env = Cloudflare.Env;
export const runtime = () => env;
export const id = () => crypto.randomUUID();
export const now = () => new Date().toISOString();
export const json = (data: unknown, status = 200) => Response.json(data, { status, headers: { "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" } });
export const text = (value: unknown, max = 120000) => String(value ?? "").trim().slice(0, max);
export const parse = <T>(value: string, fallback: T): T => { try { return JSON.parse(value) as T; } catch { return fallback; } };
export function safeError(error: unknown) { return error instanceof Error ? error.message.replace(/[A-Za-z0-9_-]{24,}/g, "[保護済み]").slice(0, 240) : "処理中に問題が発生しました。"; }
export async function fetchWithRetry(url: string, init: RequestInit, attempts = 2) { let last: unknown; for (let i = 0; i <= attempts; i++) { try { const controller = new AbortController(), timer = setTimeout(() => controller.abort(), 45000); const response = await fetch(url, { ...init, signal: controller.signal }); clearTimeout(timer); if (response.ok || response.status < 500 || i === attempts) return response; last = new Error(`外部サービスが応答しません (${response.status})`); } catch (error) { last = error; } await new Promise(resolve => setTimeout(resolve, 500 * (i + 1))); } throw last; }
export const wordTokens = (value: string) => [...new Set(value.replace(/https?:\/\/\S+/g, " ").split(/[\s、。！？,.()「」『』【】【：]+/).filter(token => token.length >= 3 && token.length <= 40))];
export function makeCandidates(project: Record<string, string>) { const seed = wordTokens(`${project.youtube_title} ${project.direction} ${project.transcript}`).slice(0, 10); return (seed.length ? seed : [project.youtube_title || "対談内容"]).slice(0, 5).map((keyword, index) => ({ keyword, related_keywords: JSON.stringify(seed.filter(item => item !== keyword).slice(0, 4)), search_intent: index % 2 ? "比較・検討" : "情報収集", reader: "動画テーマについて具体的な一次情報を求める読者", angle: `${project.challenger_name || "出演者"}の発言を起点に、${keyword}を具体的に整理する`, relevance: "文字起こし・出演者情報に含まれる語句から候補化", duplication_risk: index ? "medium" : "low" })); }
export function articleDraft(project: Record<string, string>, candidate: Record<string, string>) { const speaker = [project.challenger_name && `${project.challenger_name}${project.challenger_company ? `（${project.challenger_company}）` : ""}`, project.special_guest && `${project.special_guest}（スペシャルゲスト）`, project.mc_name && `${project.mc_name}（MC）`].filter(Boolean).join("、") || "動画内の出演者"; const quote = text(project.transcript, 700).replace(/\s+/g, " "); const title = `${candidate.keyword}を対談の一次情報から読み解く`;
  const evidence = JSON.stringify([{ speaker, role: "入力された出演者情報", excerpt: quote, source: project.youtube_url || project.youtube_title || "文字起こし" }]);
  return { title, title_tag: title.slice(0, 58), meta_description: `${project.youtube_title || "対談動画"}の文字起こしを一次情報に、${candidate.keyword}について出演者の発言を整理します。`.slice(0, 120), slug: candidate.keyword.toLowerCase().replace(/[^a-z0-9\u3040-\u30ff\u4e00-\u9fff]+/g, "-").replace(/^-|-$/g, "") || "video-primary-information", catch_copy: "対談で語られた一次情報を、読者の理解につながる形へ。", body_html: `<p>この記事は「${project.youtube_title || "動画対談"}」の文字起こしを主な一次情報として構成しています。</p><h2>${candidate.keyword}について、対談で語られたこと</h2><p>${quote}</p><h2>発言から読み取れる実務上のポイント</h2><p>${speaker}が動画内で語った内容を、文脈を変えない範囲で整理します。動画内にない数値・事実・効果は追加していません。</p><h2>公開前に確認したいこと</h2><ul><li>発言者と役職の表記が動画・文字起こしと一致しているか</li><li>引用・要約が発言の文脈と矛盾していないか</li><li>追加した表現に一次情報の裏付けがあるか</li></ul>`, evidence_json: evidence, image_suggestions_json: JSON.stringify([{ heading: `${candidate.keyword}について、対談で語られたこと`, prompt: "対談のテーマを説明する、事実を追加しない抽象的な編集写真", alt: `${candidate.keyword}について対談内容を説明する画像` }]), quality_json: JSON.stringify({ evidence: "PASS", fabricationRisk: "LOW", note: "公開前に発言と文字起こしを照合してください。" }) }; }
