const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
const safeHtml = (value) => String(value || "").replace(/<script\b[\s\S]*?<\/script>/gi, "").replace(/\s(?:href|src)\s*=\s*["']\s*javascript:[^"']*["']/gi, "");
export const normalizeTag = (value) => String(value || "").normalize("NFKC").trim().toLowerCase();
export const detectSeoPlugin = (namespaces = []) => !Array.isArray(namespaces) ? "UNKNOWN" : namespaces.some((value) => /rank-math/i.test(value)) ? "RANK_MATH" : namespaces.some((value) => /yoast/i.test(value)) ? "YOAST" : "NONE";
export function createSeoMetaProvider(plugin, supported = false) {
  const provider = plugin === "RANK_MATH" ? "RankMathSeoProvider" : plugin === "YOAST" ? "YoastSeoProvider" : "NativeSeoLoopProvider";
  const syncStatus = plugin === "NONE" ? "NOT_APPLICABLE" : plugin === "UNKNOWN" || !supported ? "SEO_PLUGIN_SYNC_NOT_AVAILABLE" : "PENDING";
  return { provider, plugin, native: true, supported: Boolean(supported), syncStatus, canonicalStatus: "CANONICAL_STORED_IN_SEO_LOOP", schemaStatus: "SCHEMA_OUTPUT_NOT_AVAILABLE" };
}
const pluginMetaPayload = (plugin, meta = {}, title, description) => {
  const fields = plugin === "RANK_MATH" ? ["rank_math_title", "rank_math_description"] : plugin === "YOAST" ? ["_yoast_wpseo_title", "_yoast_wpseo_metadesc"] : [];
  if (!fields.length || !fields.every((field) => Object.prototype.hasOwnProperty.call(meta || {}, field))) return null;
  return plugin === "RANK_MATH" ? { rank_math_title:title, rank_math_description:description } : { _yoast_wpseo_title:title, _yoast_wpseo_metadesc:description };
};
export function selectTags(candidates, existingTags, limit = 5) {
  const existing = new Map((existingTags || []).map((tag) => [normalizeTag(tag.name), tag]));
  const used = new Set();
  return (candidates || []).map(normalizeTag).filter(Boolean).filter((tag) => !used.has(tag) && used.add(tag)).slice(0, Math.max(1, Math.min(10, limit))).map((tag) => existing.get(tag) || null).filter(Boolean);
}
export function createMockWordPressAdapter({ posts = [], categories = [], tags = [], failures = [], namespaces = [] } = {}) {
  const store = new Map(posts.map((post) => [String(post.id), structuredClone(post)])); let nextId = Math.max(0, ...posts.map((post) => Number(post.id) || 0)) + 1; let calls = 0;
  const maybeFail = async () => { const status = failures[calls++]; if (!status) return; if (status === "timeout") throw new Error("timeout"); const error = new Error(`WordPress ${status}`); error.status = status; throw error; };
  const save = async (post, id) => { await maybeFail(); const postId = id || String(nextId++), prior = store.get(postId) || {}; const next = { ...prior, ...structuredClone(post), id: postId, slug: prior.slug || post.slug || `post-${postId}`, link: `https://mock.wordpress.test/?p=${postId}` }; store.set(postId, next); return structuredClone(next); };
  return { async fetchPost(id) { await maybeFail(); const post = store.get(String(id)); if (!post) { const error = new Error("WordPress 404"); error.status = 404; throw error; } return structuredClone(post); }, async create(post) { return save({ ...post, content: safeHtml(post.content) }); }, async update(id, post) { if (!store.has(String(id))) { const error = new Error("WordPress 404"); error.status = 404; throw error; } return save({ ...post, content: safeHtml(post.content) }, String(id)); }, async fetchCategories() { await maybeFail(); return structuredClone(categories); }, async fetchTags() { await maybeFail(); return structuredClone(tags); }, async detectSeoPlugin() { return detectSeoPlugin(namespaces); }, async syncSeoPlugin(id, { plugin, seoTitle, metaDescription }) { if(plugin==="NONE")return {plugin,pluginSyncStatus:"NOT_APPLICABLE",pluginSyncErrorCode:null}; const post=await this.fetchPost(id), meta=pluginMetaPayload(plugin,post.meta,seoTitle,metaDescription); if(!meta)return { plugin, pluginSyncStatus:"SEO_PLUGIN_SYNC_NOT_AVAILABLE", pluginSyncErrorCode:"SEO_PLUGIN_SYNC_NOT_AVAILABLE" }; await this.updateSeoMeta(id,meta); return { plugin, pluginSyncStatus:"SUCCESS", pluginSyncErrorCode:null }; }, async assignFeaturedMedia(id, featured_media) { return save({ featured_media }, String(id)); }, async updateSeoMeta(id, meta) { await maybeFail(); return save({ seo_meta: meta, meta:{...(store.get(String(id))?.meta||{}),...meta} }, String(id)); }, async rollback(id, snapshot) { return save(snapshot, String(id)); }, inspect() { return { posts: [...store.values()].map(structuredClone), calls }; } };
}
export function createHttpWordPressAdapter({ siteUrl, username, applicationPassword, fetchImpl = fetch }) {
  const base = String(siteUrl || "").replace(/\/$/, ""); const authorization = `Basic ${btoa(`${username}:${applicationPassword}`)}`;
  const request = async (path, init = {}) => { for (let attempt = 0; attempt < 3; attempt++) { const response = await fetchImpl(`${base}/wp-json/wp/v2/posts${path}`, { ...init, headers: { Authorization: authorization, "Content-Type": "application/json", ...(init.headers || {}) } }); if (response.ok || ![429, 500, 502, 503, 504].includes(response.status) || attempt === 2) return response; await sleep(250 * (attempt + 1)); } };
  const json = async (response) => { const body = await response.json().catch(() => ({})); if (!response.ok) { const error = new Error(body.message || `WordPress ${response.status}`); error.status = response.status; throw error; } return body; };
  return { async fetchPost(id) { return json(await request(`/${encodeURIComponent(id)}?context=edit`, { method: "GET" })); }, async create(post) { return json(await request("", { method: "POST", body: JSON.stringify(post) })); }, async update(id, post) { return json(await request(`/${encodeURIComponent(id)}`, { method: "POST", body: JSON.stringify(post) })); }, async fetchCategories() { const response = await fetchImpl(`${base}/wp-json/wp/v2/categories?context=edit&per_page=100`, { headers: { Authorization: authorization } }); return json(response); }, async fetchTags() { const response = await fetchImpl(`${base}/wp-json/wp/v2/tags?context=edit&per_page=100`, { headers: { Authorization: authorization } }); return json(response); }, async detectSeoPlugin() { const response=await fetchImpl(`${base}/wp-json`,{headers:{Authorization:authorization}}); if(!response.ok)return "UNKNOWN"; const root=await response.json().catch(()=>null); return detectSeoPlugin(root?.namespaces); }, async syncSeoPlugin(id, { plugin, seoTitle, metaDescription }) { if(plugin==="NONE")return {plugin,pluginSyncStatus:"NOT_APPLICABLE",pluginSyncErrorCode:null}; const post=await this.fetchPost(id), meta=pluginMetaPayload(plugin,post.meta,seoTitle,metaDescription); if(!meta)return { plugin, pluginSyncStatus:"SEO_PLUGIN_SYNC_NOT_AVAILABLE", pluginSyncErrorCode:"SEO_PLUGIN_SYNC_NOT_AVAILABLE" }; await this.updateSeoMeta(id,meta); return { plugin, pluginSyncStatus:"SUCCESS", pluginSyncErrorCode:null }; }, async updateSeoMeta(id, meta) { return json(await request(`/${encodeURIComponent(id)}`, { method:"POST", body:JSON.stringify({meta}) })); } };
}
